### PR TITLE
Downgrade jpeg from 9c to 8d

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/348

**Comment by jakirkham** [comment]
Probably needs another branch.

**Comment by hmaarrfk** [comment]
does it? I thought we where going to deprecate the use of 9 alltogether.

**Comment by ocefpaf** [comment]
> does it? I thought we where going to deprecate the use of 9 alltogether.

I'm not sure we can. I recall that we have some Met/Ocean packages that require 9.

**Comment by hmaarrfk** [comment]
if somebody could create a branch for me that would be appreciated. I can retarget. though, I think the speedups from turbo might be enough to make those packages revert to the v8 api.

**Comment by ocefpaf** [comment]
> if somebody could create a branch for me that would be appreciated. I can retarget. though, I think the speedups from turbo might be enough to make those packages revert to the v8 api.

Done!

**Comment by hmaarrfk** [comment]
So this can be merged correct?

**Pull request merged**
