### PR TITLE
Add @jakirkham as a maintainer

### PR DESCRIPTION
**Pull request by jakirkham**
Adds me as a maintainer.

### CODE REVIEW

**Comment by jakirkham** [comment]
Linter is complaining about this [line](https://github.com/conda-forge/jpeg-feedstock/blob/7d1b8e1dcf2303762668e3a40bb725c8d275ee39/recipe/meta.yaml#L28). We can ignore it.

**Comment by gillins** [comment]
This line came from @patricksnape (see https://github.com/conda-forge/staged-recipes/pull/355) - another workaround to get the right version of VC!

**Comment by jakirkham** [comment]
No worries. Not saying it should be changed. Quite the opposite. Just noting what is going on for people in the future (or in a few hours :wink:).

**Comment by jakirkham** [comment]
If you have no objections, would you please merge this, @gillins?

**Comment by gillins** [comment]
:smile: I wonder if there should be a better syntax for getting Python for testing?

**Comment by jakirkham** [comment]
We are working on a VC package in this PR ( https://github.com/conda-forge/staged-recipes/pull/363 ). It will ultimately replace this Python stuff. Also, it will open the door to other VC versions that don't have a supported CPython version, but are otherwise useful (e.g. building C/C++ projects).

**Pull request merged**
